name: KBAnalysis

on:
  issues:
    types:
     - opened
     - reopened
    
permissions:
  contents: read

jobs:
  Analysis:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          repository: h0x0er/secure-workflows
      - name: KBAnalysis
        uses: h0x0er/kbanalysis@enchancements
        with:
          github-token: ${{secrets.GITHUB_TOKEN }}
          issue-id: ${{ github.event.issue.number}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          body: "Fixes #${{github.event.issue.number}}"
          commit-message: "added KB for issue#${{github.event.issue.number}}"
          title: "Add KB for issue${{github.event.issue.number}}"
          branch: "issue#${{github.event.issue.number}}"
