name: KBAnalysis

on:
  issues:
    types:
     - opened
     - reopened
    
permissions:
  contents: write
  pull-requests: write

jobs:
  Analysis:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: KBAnalysis
        uses: h0x0er/kbanalysis@enchancements
        with:
          github-token: ${{secrets.GITHUB_TOKEN }}
          issue-id: ${{ github.event.issue.number}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          body: "Add KB for #${{github.event.issue.number}}"
          branch: "issue#${{github.event.issue.number}}"
