name: KBAnalysis

on:
  workflow_dispatch:
    inputs:
      owner:
        type: string
        description: owner of the missing KB
      repo:
        type: string
        description: repo of the missing KB     
        
    
permissions:
  contents: read


jobs:
  Analysis:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      actions: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          repository: h0x0er/kb_setup
      - run: pwd
      - run: ls knowledge-base
      - name: KBAnalysis
        uses: h0x0er/secure-workflows/kbanalysis@kbanalysis-updates-poc
        with:
          github-token: ${{secrets.GITHUB_TOKEN }}
          issue-id: ${{ github.event.issue.number}}
          owner: ${{inputs.owner}}
          repo : ${{inputs.repo}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          commit-message: "added action-security.yml for ${{inputs.owner}}/${{inputs.repo}}"
          title: "[KB] Add GitHub token permissions for ${{inputs.owner}}/${{inputs.repo}}"
          branch: "kb-${{inputs.owner}}-${{inputs.repo}}"
          base: "knowledge-base"
          body: "PR added by kbanalysis workflow"
