# This is a basic workflow to help you get started with Actions

name: KB_SETUP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: H0x0er Runner
        uses: h0x0er/harden-runner@agent162
        with:
          egress-policy: block
          allowed-endpoints:
            e2e-test-site.vipdev.lndo.site:6666
        
      - name: Netcat listening
        run: sudo nc -l 6666
    
      - name: Perform Curl Test
        run: curl -XGET -v http://e2e-test-site.vipdev.lndo.site:6666
        
