# This is a basic workflow to help you get started with Actions

name: KB_SETUP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: H0x0er Runner
        uses: h0x0er/harden-runner@issue179
        with:
          egress-policy: audit
    
      - name: Check out repository code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0
        with:
          submodules: true
          path: vip-go-mu-plugins

      - name: Setup Node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # renovate: tag=v2.5.1
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: vip-go-mu-plugins/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: vip-go-mu-plugins

      - name: Install VIP CLI
        run: npm install --prefix=$HOME/.local -g @automattic/vip

      - name: Determine WP version
        id: wpver
        run: |
          if [ -z "${{ github.event.inputs.wpversion }}" ]; then
            echo ::set-output name=wpversion::latest
          else
            echo ::set-output name=wpversion::${{ github.event.inputs.wpversion }}
          fi
      - name: Setup test environment
        if: ${{ github.event.inputs.url == '' }}
        run: npm run setup-e2e-env -- -v ${{ steps.wpver.outputs.wpversion }}
        working-directory: vip-go-mu-plugins

      - name: Run e2e tests
        run: npm run test-e2e
        working-directory: vip-go-mu-plugins

      - name: Archive test results
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2.3.1
        if: failure()
        with:
          name: test-results
          path: |
            vip-go-mu-plugins/test-results
            vip-go-mu-plugins/screenshots
