# This is a basic workflow to help you get started with Actions

name: KB_SETUP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
#       - name: H0x0er Runner
#         uses: h0x0er/harden-runner@issue170
#         with:
#           egress-policy: block
#           allowed-endpoints: dns.google.com:443
      - name: Pre DIG
        run : dig github.com
      - name: Harden Runner
        uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24
        with:
          egress-policy: block
          allowed-endpoints: 
            dns.google.com:443
            github.com:443
          
      - name: Post DIG
        run: dig github.com
      - name: Rerun DIG
        run : dig github.com
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2


