name: Trivy Scanner
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    
      - uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v3

#       - run: docker pull aquasec/trivy
#       - run: docker run aquasec/trivy server &
      - run: wget --quiet https://github.com/aquasecurity/trivy/releases/download/v0.36.1/trivy_0.36.1_Linux-64bit.tar.gz -O /tmp/trivy.tar.gz
      - run: cd /tmp; tar xf trivy.tar.gz
      - run: ls /tmp
      - run: sudo mv /tmp/trivy /usr/local/sbin
      - run: trivy server &
      
      
