name: Trivy Scanner
on:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    
      - uses: step-security/harden-runner@18bf8ad2ca49c14cbb28b91346d626ccfb00c518 # v2.1.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@v3

      - run: docker pull aquasec/trivy
      - run: docker run aquasec/trivy server &
